name: Build kernel modules
description: "Builds Kernel modules and dtbs"

runs:
  using: composite
  steps:
    - name: Create custom defconfig fragment
      shell: bash
      run: |
        set -euo pipefail

        if [[ "${TREE}" == "mixed" ]]; then
          KERNEL_DIR="msm-kernel"
        else
          KERNEL_DIR="common"
        fi
        cd "${ROOT_DIR}/${KERNEL_DIR}"
        touch arch/arm64/configs/modules.config

    - name: Add nethunter specfic drivers already present in kernel to be built as modules
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${TREE}" == "mixed" ]]; then
          KERNEL_DIR="msm-kernel"
        else
          KERNEL_DIR="common"
        fi
        cd "${ROOT_DIR}/${KERNEL_DIR}"
        
        # Realtek drivers
        ./scripts/config --file arch/arm64/configs/modules.config \
          -e CONFIG_WLAN_VENDOR_REALTEK

        # ATH drivers
        ./scripts/config --file arch/arm64/configs/modules.config \
          -e CONFIG_WLAN_VENDOR_ATH \
          -m CONFIG_ATH_COMMON \
          -m CONFIG_ATH9K \
          -m CONFIG_ATH9K_HW \
          -m CONFIG_ATH9K_HTC \
          -m CONFIG_ATH9K_COMMON \
          -m CONFIG_ATH10K \
          -m CONFIG_ATH10K_USB \
          -m CONFIG_ATH11K

        # Mediatek drivers
        ./scripts/config --file arch/arm64/configs/modules.config -k \
          -e CONFIG_WLAN_VENDOR_MEDIATEK \
          -m CONFIG_MT7601U \
          -m CONFIG_MT76_CORE \
          -m CONFIG_MT76_USB \
          -m CONFIG_MT76x02_LIB \
          -m CONFIG_MT76x02_USB \
          -m CONFIG_MT76_CONNAC_LIB \
          -m CONFIG_MT7603E \
          -m CONFIG_MT76x2E \
          -m CONFIG_MT76x2U \
          -m CONFIG_MT76x0U \
          -m CONFIG_MT76x0E \
          -m CONFIG_MT7615_COMMON \
          -m CONFIG_MT7615E \
          -m CONFIG_MT7663_USB_SDIO_COMMON \
          -m CONFIG_MT7663U \
          -m CONFIG_MT7663S \
          -m CONFIG_MT7915E \
          -m CONFIG_MT7921E

        # Other configs
        ./scripts/config --file arch/arm64/configs/modules.config \
          -e CONFIG_MAC80211_LEDS \
          -e CONFIG_MAC80211_RC_MINSTREL \
          -m CONFIG_CAN_SLCAN

    - name: Add my kernel patches to msm kernel
      shell: bash
      run: |
        set -euo pipefail
        echo "Applying kernel patches to device kernel from my repo..."
        if [[ "${TREE}" == "mixed" ]]; then
          KERNEL_DIR="msm-kernel"
        else
          KERNEL_DIR="common"
        fi
        cd "${ROOT_DIR}/${KERNEL_DIR}"

        if [[ -d "${KERNEL_PATCHES}/kernel_patches/${CODENAME}-${OS_SHORT}/msm" ]]; then
          # We don't need to handle this actually but just in case if someone left an empty dir
          shopt -s nullglob

          for patch in "${KERNEL_PATCHES}/kernel_patches/${CODENAME}-${OS_SHORT}/msm"/*.patch; do
            if patch -p1 -s -N -F0 --dry-run -i "$patch" >/dev/null 2>&1; then
              echo "Applying patch: ${patch}"
              patch -p1 -N -F0 -i "${patch}"
            else
              echo "Skipping patch (conflicts or already applied): ${patch}"
            fi
          done

          shopt -u nullglob
        fi


    - name: Add rtw88 modules
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${TREE}" == "mixed" ]]; then
          KERNEL_DIR="msm-kernel"
        else
          KERNEL_DIR="common"
        fi
        cd "${ROOT_DIR}/${KERNEL_DIR}/drivers/net/wireless/realtek/"
        rm -rf rtw88
        git clone https://github.com/lwfinger/rtw88.git
        sed -i 's/$(CONFIG_RTW88)/m/g' Makefile
        sed -i '/^source "drivers\/net\/wireless\/realtek\/rtw88\/Kconfig"$/s/.*/ /' Kconfig
